### ISSUE TITLE
error generating frontend from maven

### ISSUE THREAD

**Issue by enricjaen** [gregturn/spring-a-gram#65]
Hi Greg, 

I get the next error in maven when I run "mvn install" . Any idea please? 
Also, I have managed to run the frontend but the gallery is empty. Any idea please?

Also I don't understand why this frontend needs node?

Regards,
Enric

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-a-gram-frontend 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.20:install-node-and-npm (install node and npm) @ spring-a-gram-frontend ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.416 s
[INFO] Finished at: 2015-07-13T13:50:35+02:00
[INFO] Final Memory: 17M/175M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm (install node and npm) on project spring-a-gram-frontend: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm: org/slf4j/helpers/MarkerIgnoringBase
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:0.0.20
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Usuario/.m2/repository/com/github/eirslett/frontend-maven-plugin/0.0.20/frontend-maven-plugin-0.0.20.jar
[ERROR] urls[1] = file:/C:/Users/Usuario/.m2/repository/com/github/eirslett/frontend-plugin-core/0.0.20/frontend-plugin-core-0.0.20.jar
[ERROR] urls[2] = file:/C:/Users/Usuario/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[3] = file:/C:/Users/Usuario/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[4] = file:/C:/Users/Usuario/.m2/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar
[ERROR] urls[5] = file:/C:/Users/Usuario/.m2/repository/org/tukaani/xz/1.2/xz-1.2.jar
[ERROR] urls[6] = file:/C:/Users/Usuario/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[7] = file:/C:/Users/Usuario/.m2/repository/org/apache/httpcomponents/httpclient/4.3.1/httpclient-4.3.1.jar
[ERROR] urls[8] = file:/C:/Users/Usuario/.m2/repository/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar
[ERROR] urls[9] = file:/C:/Users/Usuario/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[ERROR] urls[10] = file:/C:/Users/Usuario/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
[ERROR] urls[11] = file:/C:/Users/Usuario/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[12] = file:/C:/Users/Usuario/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[13] = file:/C:/Users/Usuario/.m2/repository/com/google/guava/guava/10.0.1/guava-10.0.1.jar
[ERROR] urls[14] = file:/C:/Users/Usuario/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[15] = file:/C:/Users/Usuario/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[16] = file:/C:/Users/Usuario/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[17] = file:/C:/Users/Usuario/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar
[ERROR] urls[18] = file:/C:/Users/Usuario/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[19] = file:/C:/Users/Usuario/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[20] = file:/C:/Users/Usuario/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[21] = file:/C:/Users/Usuario/.m2/repository/com/googlecode/slf4j-maven-plugin-log/slf4j-maven-plugin-log/1.0.0/slf4j-maven-plugin-log-1.0.0.jar
[ERROR] urls[22] = file:/C:/Users/Usuario/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[23] = file:/C:/Users/Usuario/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.slf4j.helpers.MarkerIgnoringBase
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by gregturn** [comment]
Looks like some type of maven dependency resolution issue. Either try again, or if you are behind a proxy or other such network configuration, there may be other requirements to make resolution start working again. If it continues to fail, you can reopen this ticket, and put more details such your own network configuration.

As for why I use node, it's to use tools like npm and bower for JavaScript modules used in the frontend app. The frontend-maven-plugin allows anyone to check out the project and build the app without having to install the node toolset. It downloads node for you, etc. For those that actually want to develop the frontend, that person would need those tools installed locally. But then again, any frontend developer that wasn't a Java developer by day, would probably have the proper tools. It's simply an alternative to something like WebJars.

1. If you look at https://github.com/gregturn/spring-a-gram/blob/master/spring-a-gram-frontend/pom.xml#L43, then you'll see the target destination for packages to be install, a path the Spring Boot will automatically serve up as a static resource.
2. If you look in https://github.com/gregturn/spring-a-gram/tree/master/spring-a-gram-frontend/src/main/resources/static, these are the fixed resources that will also be included in the client-side code.

I personally find this approach more saavy than using WebJars. When I need help from the JavaScript community, I know I'm getting industry-accepted approaches to things.

Cheers!
