### ISSUE TITLE
doubt about forwarding from frontend to backend 

### ISSUE THREAD

**Issue by enricjaen** [gregturn/spring-a-gram#66]
Hello
The aplicaction is configured by default:

back-end --> localhost:9000/api
front-end --> locahost:8080

If I go to "localhost:8080/api/items"  the request is forwared to "localhost:9000/api/items" 

I don't undestand which is the mechanism that is forwarding 8080 to 9000 ?

**Comment by gregturn** [comment]
For starters, you are checking out our demo app that is being overhauled for SpringOne in September. So, you've caught us in transition where not all the docs are yet updated.

To answer your question, it the Zuul proxy stuff from Spring Cloud being used. If you look at the commits, you can probably track it down. I'll leave it at that, given there are plans to update the docs using Spring Rest Docs as well.

**Comment by enricjaen** [comment]
Thanks, it's clear now.
