### ISSUE TITLE
Can I test with local pc?

### ISSUE THREAD

**Issue by ishara** [gregturn/spring-a-gram#82]
How can I run local env,if possible please update read me.

Thank You

**Comment by gregturn** [comment]
You need to run:

1. EurekaServiceDiscoveryApplication
1. BackendApplication
1. MongoDbFileServiceAppliation (and have MongoDB up)

To enable S3 file storage, run S3FileServiceAppliation with BUCKET pointing at an S3 location for files (without the s3:// prefix), CLOUD_AWS_CREDENTIALS_ACCESSKEY, and CLOUD_AWS_CREDENTIALS_SECRETKEY configured.

By default FrontendApplication runs in "MongoDB" mode, looking for the MongoDB service. To flip it to S3, add SPRING_PROFILES_ACTIVE=s3.

To enable HTTP BASIC, add "basic" to the list of profiles.
